version: '3'

services:
  message-store:
    image: message-store:0.0.1-SNAPSHOT
    container_name: message_store_service
    environment:
      MESSAGE_DB_HOST: db
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: message_db
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: messages
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
    driver: local