spring:
  profiles:
    active: local-dev

---
spring.profiles: local-dev
spring:
  profiles:
    include: local-postgresql-credentials,debug
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/messages

---
spring:
  profiles: local-postgresql-credentials
  datasource:
    username: postgres
    password: changeme

---
spring:
  profiles: debug
logging:
  level:
    com.alevel.java.messagestore: debug